### ISSUE TITLE
You swapped your param names when calling a function

### ISSUE THREAD

**Issue by unoriginalscreenname** [Maximilian-Winter/llama-cpp-agent#1]
Hi!  I just checked out your library and ran into an issue, but for once I have a fix to offer!

I was getting an error on the example_embodied_function_calling file and noticed that you had the parameter names reversed:

if function_call["Function"] == "write-text-file":
    call_parameters = function_call["function_params"]
    call = WriteTextFile(**call_parameters)
    call.run()

should be:

if function_call["function_params"] == "write-text-file":
    call_parameters = function_call["Function"]
    call = WriteTextFile(**call_parameters)
    call.run()
    
 I think it's that way on all the function calls.  Hope that helps!  This looks like a very cool library with really great examples.  thank you so much for putting it together.

**Comment by Maximilian-Winter** [comment]
The actual problem was a missing parameter I added to the grammar generator. Thank you for pointing that out!!! I fixed it in all examples. Sorry.
