### ISSUE TITLE
Condition  in calling_agent seems to be wrong

### ISSUE THREAD

**Issue by palkokec** [Maximilian-Winter/llama-cpp-agent#10]
Not 100% sure, but was experiencing the issues using llama_llm of type *Llama* and generation setting of type *LlamaLLMGenerationSettings*.
This combination always throw error:
> "Wrong generation settings for llama-cpp-python, use LlamaLLMGenerationSettings under llama_cpp_agent.llm_settings!"

Looking in the code it seems Line 131 here 
https://github.com/Maximilian-Winter/llama-cpp-agent/blame/a7442166e326645c5198113cc643bfbf00fe4ffa/src/llama_cpp_agent/function_calling_agent.py#L131

Should be changed to:
```
if (isinstance(llama_llm, Llama) or isinstance(llama_llm, LlamaLLMSettings)) and isinstance(
                llama_generation_settings, LlamaCppGenerationSettings):
```
*(A or B) and C* as current code executes as *A or (B and C)* without brackets

**Comment by Maximilian-Winter** [comment]
Thanks, I plan to release a new version soon and will incorporate that.

**Comment by krlohnes** [comment]
This also seems to be an issue with the StructuredOutputAgent.

**Comment by Maximilian-Winter** [comment]
Is fixed in the latest release
