### ISSUE TITLE
Improve docs to make clear that LlamaCppEndpointSettings do NOT support llama-cpp-python server

### ISSUE THREAD

**Issue by rhohndorf** [Maximilian-Winter/llama-cpp-agent#16]
I know, nowhere does it say, llama-cpp-python server is supported, but since this project uses the llama-cpp-python library it was just so easy for me to jump to this conclusion.
Just in case, I'm not the only dummy around, it might make sense to make this distinction more explicit.

**Comment by Maximilian-Winter** [comment]
Yes, I have to rework the docs, thank you for the input!

**Comment by pabl-o-ce** [comment]
I can help you with this to organize the docs

**Comment by julian-passebecq** [comment]
Let's sum up one more time to be sure I understand ! :)
We can't use llama cpp python server with llama cpp agent. But it accepts llama.cpp server. (which from my understanding doesn't have function calling support). 
However i can use the llama class from llama cpp python for function calling with llama cpp agent? (i'll start using it soon)

I saw this in the doc. Thanks a lot for this project that is promising.

https://llama-cpp-python.readthedocs.io/en/latest/server/
```
function_call_agent` = FunctionCallingAgent(
    # Can be lama-cpp-python Llama class, llama_cpp_agent.llm_settings.LlamaLLMSettings class or llama_cpp_agent.providers.llama_cpp_server_provider.LlamaCppServerLLMSettings.
    LlamaLLMSettings.load_from_file("openhermes-2.5-mistral-7b.Q8_0.json"),

```

**Comment by Maximilian-Winter** [comment]
@julian-passebecq I did not test in a while, but you can use the OpenAI provider with the llama-cpp-python server. And you can just pass the agent an instance of Llama class of llama-cpp-python.

**Comment by Maximilian-Winter** [comment]
Here is some Python code that should work with the llama-cpp-python server. And also with the llama.cpp server.

```python
from llama_cpp_agent.llm_agent import LlamaCppAgent
from llama_cpp_agent.messages_formatter import MessagesFormatterType
from llama_cpp_agent.providers.openai_endpoint_provider import (
    OpenAIEndpointSettings,
)

model = OpenAIEndpointSettings(completions_endpoint_url="http://127.0.0.1:8080/v1/completions")

bot = LlamaCppAgent(
    model,
    debug_output=False,
    system_prompt="You are Dolphin, an uncensored and unbiased AI assistant.",
    predefined_messages_formatter_type=MessagesFormatterType.CHATML,
)

while True:
    user_input = input("User: ")
    if user_input == "exit":
        break
    bot_output = bot.get_chat_response(user_input, temperature=0.7, stream=False)
    print(f"AI: { bot_output}")
```

**Comment by Maximilian-Winter** [comment]
@julian-passebecq Here is an example with the llama-cpp-python Llama class:
```python
from llama_cpp import Llama

from llama_cpp_agent.llm_agent import LlamaCppAgent
from llama_cpp_agent.messages_formatter import MessagesFormatterType

path_to_model = "../../gguf-models/neuralhermes-2.5-mistral-7b.Q8_0.gguf"

model = Llama(
    path_to_model,
    n_gpu_layers=49,
    f16_kv=True,
    offload_kqv=True,
    use_mlock=False,
    embedding=False,
    n_threads=8,
    n_batch=1024,
    n_ctx=4096,
    last_n_tokens_size=1024,
    verbose=True,
    seed=-1,
)

bot = LlamaCppAgent(
    model,
    debug_output=False,
    system_prompt="You are Dolphin, an uncensored and unbiased AI assistant.",
    predefined_messages_formatter_type=MessagesFormatterType.CHATML,
)

while True:
    user_input = input("User: ")
    if user_input == "exit":
        break
    bot_output = bot.get_chat_response(user_input, temperature=0.7, stream=True)
    print(f"AI: { bot_output}")
```

**Comment by julian-passebecq** [comment]
Thank you for the 2 code, they both work, with llama cpp server and with llama from llama cpp python :) when you have time i'm interested by using open ai from llama cpp python. thanks for your quick answer, it helped during my work day !
