### ISSUE TITLE
Error: AttributeError: type object 'Book' has no attribute 'model_fields'

### ISSUE THREAD

**Issue by ibehnam** [Maximilian-Winter/llama-cpp-agent#29]
I've been trying to use the package. Trying the example shown here throws the said error:

https://github.com/Maximilian-Winter/llama-cpp-agent/blob/master/examples/02_Structured_Output/book_dataset_creation.py 

More details:

```
generate_field_markdown(field_name, field_type, model, depth, documentation_with_field_description)
   (...)
--> [752](https://file+.vscode-resource.vscode-cdn.net.../.venv/lib/python3.12/site-packages/llama_cpp_agent/gbnf_grammar_generator/gbnf_grammar_from_pydantic_models.py:752) field_info = model.model_fields.get(field_name)
```

**Comment by Maximilian-Winter** [comment]
Hi, I just released a new version and tested it. It should work now.

**Comment by ibehnam** [comment]
@Maximilian-Winter Thanks, that seems to have solved the problem.
