### ISSUE TITLE
FunctionCallingAgent.generate_response lacking return statement

### ISSUE THREAD

**Issue by ebarrragn** [Maximilian-Winter/llama-cpp-agent#38]
The method FunctionCallingAgent.generate_response, it seems storing values in the variable 'result', but afterwards it doesn't return it. Actually, if that is not the intended purpose of 'result', it adds useful functionality, as now it is easy to programmatically use the response by the LLM.

The place I added the return statement is line 388, function_calling_agent.py

A big thank you for your work.

**Comment by Maximilian-Winter** [comment]
I will look at it and then decicde.

**Comment by Maximilian-Winter** [comment]
@ebarrragn Actually it isn't intended to return a response, but I added it, like you did, for people who need it.

**Comment by Maximilian-Winter** [comment]
@ebarrragn Is in the latest release.
