### ISSUE TITLE
Some about documentation page of project.

### ISSUE THREAD

**Issue by svjack** [Maximilian-Winter/llama-cpp-agent#49]
I think we should add the documentation link "https://llama-cpp-agent.readthedocs.io/en/latest/" on the top of README.md in repo.

And some example, lack technical guidance, such as difference between 
[simple_function_calling.py](https://github.com/Maximilian-Winter/llama-cpp-agent/blob/master/examples/03_Function_Calling/simple_function_calling.py)
[parallel_function_calling.py](https://github.com/Maximilian-Winter/llama-cpp-agent/blob/master/examples/03_Function_Calling/parallel_function_calling.py)

Some discussion about relatively independent part of the project.
Such as 
[hermes_2_pro_agent.py](https://github.com/Maximilian-Winter/llama-cpp-agent/blob/master/examples/05_Agents/hermes_2_pro_agent.py)

hermes_2_pro_agent.py seems no ability of parallel_function_calling.py because it solely 
a model calling of tool calling LLM and lack  chain ability. But can run fast with the help of
 91% accuracy of function tool Function format parsing capability.

Some background introduction will make people use this project more convenient.

Can you open a discord to make us improve the project together.😊

**Comment by Maximilian-Winter** [comment]
@svjack I added some comments to simple_function_calling.py and parallel_function_calling.py to make the difference more clear.

**Comment by Maximilian-Winter** [comment]
You can use my version of the Hermes 2 Pro agent with parallel function calling and it works for the examples.
