### ISSUE TITLE
Return control after function executed

### ISSUE THREAD

**Issue by ebarrragn** [Maximilian-Winter/llama-cpp-agent#55]
I'd like to stop execution after a function has been executed, mostly to save the time taken by another LLM iteration (I have an old P40). Until now, I was telling the agent things like say '(End of message)' or so, but the final response was returned incomplete.

Looking into the code, it turns out there is a commentary talking about a 'return_control' flag that seems not implemented (correct me if I am wrong).

I have implemented it in function_calling_agent.py, line 396, method generate_response, just before the line `if agent_sent_message:`:

```
                if not isinstance(res, str):
                    if "params" in res:
                        params = res["params"]
                        if "return_control" in params:
                            if params["return_control"]:
                                break
```
I can try a pull request if that is fine.

**Comment by ebarrragn** [comment]
One example of use, I have left, commented, the original string I was returning to return control:
```
class TaskReturnYesAndFinish(BaseModel):
    """
    Return 'Yes' then the task has been completed and there is nothing else to do.
    """
    return_control: bool

    def run(self, **kwargs):
        self.return_control = True
       # Using this string before
        # retval = "You answered 'Yes' and your task is completed, say: '<|end_of_turn|>' to finish."
        retval = "You answered 'Yes' and your task is completed."
        return retval
```

**Comment by Maximilian-Winter** [comment]
@ebarrragn You can use the normal LlamaCppAgent. It will just call the function and returns the result.

**Comment by ebarrragn** [comment]
Interesting, I may not understand you. When I use it, depending on the model, they carry on calling functions until for some reason they get tired (2 to 4 iterations), or they get into an infinite cycle, I've seen that using 'Phi-3-mini-4k-instruct-q4.gguf'. Am I doing something wrong when the agent doesn't return control after one function call?

**Comment by Maximilian-Winter** [comment]
@ebarrragn Could you show me your code? I'm curious why this happens.

**Comment by ebarrragn** [comment]
Sure, I'll prepare a case example with that part only, so you don't have to grok all over the code.

**Comment by ebarrragn** [comment]
Finally, I found some time. After the changes done last weekend, my code is quite broken, will have a look at it this weekend, so I adapted one of the examples to show the issue, I just made the llm local using phi3 as model (I hope it's not nonsense) .
[function_calling_agent.py.txt](https://github.com/Maximilian-Winter/llama-cpp-agent/files/15328100/function_calling_agent.py.txt)

**Comment by ebarrragn** [comment]
The PHI3 problem seems related to llama.cpp.

**Comment by Maximilian-Winter** [comment]
You can simply use the LlamaCppAgent instead of the FunctionCallingAgent to return controll immeadeatly

**Comment by ebarrragn** [comment]
Yes, the phi3 bug confused me because even using the LlamaCppAgent, it wasn't stopping, but actually it seems to be a llama.cpp problem.
I am closing this issue.
