### ISSUE TITLE
Is it possible to add mermaid syntax grammar support?

### ISSUE THREAD

**Issue by PAHXO** [Maximilian-Winter/llama-cpp-agent#62]
I tried using Llama 3 8m to generate mermaid diagrams from text.
but they have minor syntax errors.
When I give it another pass to gpt-4 to fix the minor syntax errors. The final diagram looks great.

So, is it possible to create a GBNF or grammar support to generate Mermaid syntax?

**Comment by Maximilian-Winter** [comment]
You could write a GBNF grammar by hand.
