### ISSUE TITLE
Avoid generating newlines and spaces rules in the GBNF grammar

### ISSUE THREAD

**Issue by imalros** [Maximilian-Winter/llama-cpp-agent#64]
Maybe the feature is already there, but what I am looking for is to generate a GBNF from my Pydantic models, which avoids formatting the json with newline and space characters to optimize the llm response time. Is there a way to disable generating newline and space character in the generated grammar using `gbnf_grammar_from_pydantic_models.py`? If not, is there a reason that the spaces and newlines should be included?

**Comment by Maximilian-Winter** [comment]
@imalros The reason for the spaces is that otherwise some models will generate endless zeroes at the end of floating point numbers and other issues like that.
But I can try to look into a optional way to do it like you said.

**Comment by Maximilian-Winter** [comment]
@imalros I didn't thought about that, but I think you are right about the ```ws ::= ([ \t\n]+)```
You should be able to change it to ```ws ::= ""````
