### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by gitrodg1** [Maximilian-Winter/llama-cpp-agent#8]
I was trying to run one of the examples and one of the initial modules failed
from llama_cpp_agent.providers.llama_cpp_server_provider import LlamaCppServerLLMSettings
with the error
ModuleNotFoundError: No module named 'llama_cpp_agent.providers.llama_cpp_server_provider'
I looked in the code on GitHub and didn't see that module so I don't know if it was modified.

I did just update llama.cpp, llama-cpp-python and llama-cpp-agent to rule that out.

Thanks for the awesome job! I have gone through all the examples in Jupyter notebooks. In general most of my errors come from the server calls, access denied problems. If I run the server from llama.cpp then run the same code in the notebook, that fixes many of the server problems. If I initiate the server from llama-cpp-python with the host and port modified to match yours, I am unsuccessful in making the Jupyter notebook code run. Not sure if that is a problem with code, my computer settings or just running from within Jupyter notebooks. Even so, I have been able to make new functions run with your setup that I was unsuccessful with using other setups.

I have to admit its not clear to me how the model is specified in the examples with something like 

main_model = LlamaCppServerLLMSettings(
    completions_endpoint_url="http://127.0.0.1:8080/completion"
)

An example with some comments on how the model is selected would help (wasn't sure if there is a default model if it is not specified). I know if I initiate the server separately(llama.cpp or llama-cpp-python) I need to specify the model and parameters. I tried to find it in the code but I must have missed it. I was looking for some kind of json file it was calling so may just have missed it.

Thanks for the great work!

**Comment by Maximilian-Winter** [comment]
At the moment it always uses the default model of the provider.
And I forgot to update a example: 'llama_cpp_agent.providers.llama_cpp_server_provider' is now ' is now 'llama_cpp_agent.providers.llama_cpp_endpoint_provider'

**Comment by Maximilian-Winter** [comment]
Will push another update at the weekend.

**Comment by gitrodg1** [comment]
> Will push another update at the weekend.

I think the import also changes to import LlamaCppEndpointSettings. Using this change and using ./server from llama.cpp directory I have set up, the example worked perfectly.
